---
cache: cargo
dist: xenial
env: 
  global: 
    - CRATE_NAME=autograph
install: 
  - sudo apt update
  - sudo apt install -y clinfo libhwloc-dev ocl-icd-opencl-dev
  - clinfo
  - git clone https://github.com/pocl/pocl
  - cd pocl
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr -DENABLE_ICD=ON -DEXTRA_HOST_CLANG_FLAGS=-fPIC
  - make -j3
  - sudo make install
  - clinfo
  - source ~/.cargo/env || true
language: rust
env: TARGET=x86_64-unknown-linux-gnu
notifications: 
  email: 
    on_success: never
script:
  - cargo run
sudo: required
